version: "3.7"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./.laundry/docker/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
  kt-kata:
    build:
      context: .
      dockerfile: .laundry/docker/Dockerfile
    ports:
      - "8080:8080"

